### PR TITLE
Docs: Fix typo

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by alphapapa** [comment]
Ok, thanks.  Being a one-letter change in a comment, I'll probably wait and merge this when I prepare v0.13-pre, which probably won't be soon.

**Comment by tarsius** [comment]
This certainly isn't important but I am going through my open pull-requests (and branches, stashes ...) and this came up.

You forgot to include this in the 0.13 release. Maybe you could merge it now?

**Comment by alphapapa** [comment]
Ok, I updated the version number before merging this, and it says I'm allowed to edit the PR, but it won't let me push a rebased commit to your remote:
```
git … push -v --force-with-lease tarsiiformes refs/heads/taxy-magit-section-typos\:refs/heads/taxy-magit-section-typos
Pushing to github.com:tarsiiformes/taxy.el.git
ERROR: Permission to tarsiiformes/taxy.el.git denied to alphapapa.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
*shrug*  Anyway, if you would, please rebase it on top of the current branch, and then I'll merge it.  Thanks.

**Comment by tarsius** [comment]
It's-a me, rebase!

**Comment by alphapapa** [comment]
Thanks.

**Comment by tarsius** [comment]
Cheers!

**Pull request merged**
